export class JPushConstants {
  public static readonly REGISTRATION_ID = "registerID";
  public static readonly CODE = "code";
  public static readonly CHANNEL = "channel";
  public static readonly CHANNELID = "channelId";
  public static readonly SOUND = "sound";
  public static readonly SEQUENCE = "sequence";
  public static readonly CONNECT_ENABLE = "connectEnable";
  //电话号码
  public static readonly MOBILE_NUMBER = "mobileNumber";
  //pushTime
  public static readonly PUSH_TIME_DAYS = "pushTimeDays";
  public static readonly PUSH_TIME_START_HOUR = "pushTimeStartHour";
  public static readonly PUSH_TIME_END_HOUR = "pushTimeEndHour";
  //silenceTime
  public static readonly SILENCE_TIME_START_HOUR = "silenceTimeStartHour";
  public static readonly SILENCE_TIME_START_MINUTE = "silenceTimeStartMinute";
  public static readonly SILENCE_TIME_END_HOUR = "silenceTimeEndHour";
  public static readonly SILENCE_TIME_END_MINUTE = "silenceTimeEndMinute";
  //消息
  public static readonly MESSAGE_ID = "messageID";
  public static readonly TITLE = "title";
  public static readonly BROADCAST_TIME = "broadcastTime";
  public static readonly CONTENT = "content";
  public static readonly EXTRAS = "extras";
  public static readonly INAPPCLICKACTION = "inAppClickAction";
  public static readonly INAPPEXTRAS = "inAppExtras";
  public static readonly INAPPSHOWTARGET = "inAppShowTarget";
  //消息事件
  public static readonly NOTIFICATION_ARRIVED = "notificationArrived";
  public static readonly NOTIFICATION_OPENED = "notificationOpened";
  public static readonly NOTIFICATION_DISMISSED = "notificationDismissed";
  //通知消息
  public static readonly NOTIFICATION_EVENT_TYPE = "notificationEventType";
  public static readonly NOTIFICATION_MAX_NUMBER = "notificationMaxNumber";
  public static readonly NOTIFICATION_ID = "notificationId";
  //cmd消息
  public static readonly COMMAND = "command";
  public static readonly COMMAND_EXTRA = "commandExtra";
  public static readonly COMMAND_RESULT = "commandResult";
  public static readonly COMMAND_MESSAGE = "commandMessage";
  //地理围栏
  public static readonly GEO_FENCE_ID = "geoFenceID";
  public static readonly GEO_FENCE_INTERVAL = "geoFenceInterval";
  public static readonly GEO_FENCE_MAX_NUMBER = "geoFenceMaxNumber";
  //tag alias
  public static readonly TAG = "tag";
  public static readonly TAGS = "tags";
  public static readonly ALIAS = "alias";
  public static readonly TAG_ENABLE = "tagEnable";
  //error
  public static readonly PARAMS_NULL = "params cant be null";
  public static readonly PARAMS_ILLEGAL = "params illegal";
  public static readonly CALLBACK_NULL = "callback cant be null";
  //event
  public static readonly CONNECT_EVENT = "ConnectEvent";
  public static readonly NOTIFICATION_EVENT = "NotificationEvent";
  public static readonly INAPP_MESSAGE_EVENT = "InappMessageEvent";
  public static readonly CUSTOM_MESSAGE_EVENT = "CustomMessageEvent";
  public static readonly LOCAL_NOTIFICATION_EVENT = "LocalNotificationEvent";
  public static readonly TAG_ALIAS_EVENT = "TagAliasEvent";
  public static readonly MOBILE_NUMBER_EVENT = "MobileNumberEvent";
  public static readonly COMMAND_EVENT = "CommandEvent";
  public static readonly BADGE_NUMBER = "badge";
  public static readonly PROPERTIES = "pros";
  public static readonly IN_APP_MESSAGE_CLICK = "inappClick";
  public static readonly IN_APP_MESSAGE_SHOW = "inappShow";
}
